name: Build

on:
  pull_request:

jobs:
  validating-schemas:
    name: Validating JSON schemas are valid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate all files with json extension against ajv
        id: validation
        continue-on-error: true
        run: |
          output=$(./validate.sh)
          echo "validation_status_code=$?" >> $GITHUB_OUTPUT
          echo "validation_result=$output" >> $GITHUB_OUTPUT
          echo "test"
          echo $output


      - name: Auto Comment if 
        uses: wow-actions/auto-comment@v1
        if: always() && steps.validation.output.validation_status_code == 1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            👋 @{{ author }}
            
            Thank you for raising your pull request.
            
            Your pull request contains invalid JSON schema files. Please check the result of validation:
            
            ```
            
            ${{ steps.validation.outputs.validation_result }}
            
            ```
            
            Please fix the validation issues, otherwise this pull request cannot be accepted.
      - name: Exit GitHub actions with status code
        if: always()
        run: exit  ${{ steps.validation.outputs.validation_status_code }}
