name: Build

on:
  pull_request:

jobs:
  validating-schemas:
    name: Validating JSON schemas are valid
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install ajv-cli
        run: npm install -g ajv-cli

      - name: Validate all files with json extension against ajv
        id: validation
        run: |
          output=$(./validate.sh)
          echo "validation_result=$output" >> $GITHUB_OUTPUT
          echo $output
          exit $?

      - name: Auto Comment if 
        uses: wow-actions/auto-comment@v1
        if: ${{ failure() }}
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          pullRequestOpened: >
            👋 @{{ author }}
            
            Thank you for raising your pull request.
            
            Your pull request contains invalid JSON schema files. Please check the result of validation:
            
            ```
            
            ${{ steps.validation.outputs.validation_result }}
            
            ```
            
            Please fix the validation issues, otherwise this pull request cannot be accepted.
